### ISSUE TITLE
make it possible to save certain colors for using on all pages

### ISSUE THREAD

**Issue by pfey03** [dictyBase/dicty-components-page-editor#634]
on certain information pages, to make it easier to read, I made section headers red. But I don't like the bright red and wanted a darker red, but could not create something as a field for selection, and I don't want to write down number codes. Maybe when holding down on a color or selecting option key or such the color could be saved. Or. simple plus sign.

**Comment by wildlifehexagon** [comment]
The new color picker in the updated editor has preset colors selected based on our Material-UI theming.
